# 1. Server Configuration
server.port=${PORT:8080}

# 2. File and Payload limits (Important for large JSON/CSV files)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 3. Database Configuration
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.jpa.show-sql=true

# Allow Hibernate to create the 'users' table automatically
spring.jpa.hibernate.ddl-auto=update

# 4. Security
# Disabling default basic auth so you can test your API easily
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
# After adding the security package and its classes, we can comment the above


app.max.usage.limit=20